import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import { FaGithub, FaLinkedin } from "react-icons/fa";
import profilePic from "../public/a.png";

export default function About() {
  return (
    <div className="App">
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <hr />
      {/* <div className={styles.grid2}>
        <a href="/" className={styles.back}>
          <h2>&larr;</h2>
          <p></p>
        </a>
      </div> */}
      <main className={styles.main2}>
        <h1 className={styles.title2}>
          About Me <a href="https://nextjs.org"></a>
        </h1>
      </main>

      <div className={styles.aboutMeContainer}>
        <div className={styles.stuff}>
          <div className={styles.aboutMeImage}>
            <Image src={profilePic} layout="intrinsic" objectFit="contain" />
          </div>

          <div className={styles.aboutMeText}>
            {/* <h3>Who Am I? </h3> */}

            <p>
              {" "}
              I am a second year Computer Engineering student at the University
              of Waterloo. I am interested in many things in various different
              aspects of life, more specifically engineering and science 🦾
            </p>

            <p>
              I was born in New Delhi, India but soon moved to Canada at the age
              of 4. Growing up, I was rapidly adapting to the Western culture
              while also possessing the roots of my Indian heritage. I was able
              to read, write, and speak in 3 different languages (Hindi,
              English, and French) shortly after my move to Canada 🇮🇳🇨🇦
            </p>

            <p>
              As I grew older, I picked up a strong passion for the sport of
              basketball. Seeing and playing the sport with my brother developed
              my love for the game along with watching the Toronto Raptors of
              course. I then played the sport competitively for 8 years, even
              taking my talents to an international level 🏀
            </p>

            <p>
              In my sophomore year of highschool, I began producing music
              instrumentals as a source of recreation. During the 2020 pandemic,
              producing became very serious and I produced over thousands of
              instrumental beats. From marketing my music on Instagram, all the
              way to collaborating with Billboard Producers, I was able to sell
              my work to artists around the world while making long lasting
              connections 🎹
            </p>

            <p>
              My passion for software development continues to grow. Topics such
              as machine learning, blockchain, and even backend architecure
              spike my interest and continue to grow my love for this field on a
              daily basis. In the future, I plan to work in several fields of
              software engineering, particularly working with backend systems.
              👨🏽‍💻
            </p>

            <p></p>
          </div>
        </div>

        <footer className={styles.footer}>
          <hr />

          <a href="https://github.com/anmoltyagi1">
            <FaGithub size="2em" color="black" />
          </a>

          <a href="https://www.linkedin.com/in/anmoltyagi1/">
            <FaLinkedin size="2em" color="black" />
          </a>
        </footer>
      </div>
    </div>
  );
}
