import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import { FaGithub, FaLinkedin } from "react-icons/fa";
import profilePic from "../public/a.png";

export default function Blog() {
  return (
    <div className="App">
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <hr />
      <main className={styles.main2}>
        <h1 className={styles.title2}>
          Blog <a href="https://nextjs.org"></a>
        </h1>
        <h3>Coming Soon</h3>
      </main>
    </div>
  );
}
