import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import profilePic from "../profile.png";
import styled from "styled-components";

// const StyledProfile = styled(profilePic)`
//   width: 200px;
//   height: 10px;
//   margin: 10px;
// `;

export default function Home() {
  return (
    <div className="App">
      <Navbar />
      <hr />

      <div className={styles.container}>
        <Head>
          <title>Anmol Tyagi</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Image
            className={styles.profile}
            src={profilePic}
            width={300}
            height={300}
          />
          {/* <StyledImage src={profilePic} /> */}
          <h1 className={styles.title}>Hi I'm Anmol 👋 </h1>

          <p className={styles.description}>
            I am a{" "}
            <code className={styles.code}> student, engineer, and more </code>
          </p>

          <div className={styles.grid}>
            <a href="/about" className={styles.card}>
              <h2>Learn more about me </h2>
            </a>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </div>
  );
}
