import Head from "next/head";
import Cali from "../profile.png";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import { FaGithub, FaLinkedin } from "react-icons/fa";
import profilePic from "../public/a.png";
import Cards from "./cards";
import phue from "../public/projectPHUE.jpeg";
import piano from "../public/piano.png";
import astar from "../public/astar.jpeg";
import warzone from "../public/warzone.jpg";
import mask from "../public/mask.png";

export default function About() {
  return (
    <div className="App">
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <hr />

      <main className={styles.main2}>
        <h1 className={styles.title2}>
          Projects <a href="https://nextjs.org"></a>
        </h1>

        <h6>
          These are some of my favourite projects that I have developed. Click
          on their card to learn more about the project along with a demo of the
          project.
        </h6>
      </main>

      <div className={styles.projectContainer}>
        <Cards
          Image={astar}
          title="A* Path Finding Visualizer"
          desc="This visualizer finds the shortest distance between two marked points on a grid."
        />

        <Cards
          Image={phue}
          title="Philips Hue & PlayStation - Lights Controller"
          desc="This app allows you to control your Philips Hue lights based on the setting of your PlayStation and other devices "
        />

        <Cards
          Image={piano}
          title="Virtual Piano"
          desc="Play the piano virtually from your computer with your keyboard and mouse "
        />

        <Cards
          Image={warzone}
          title="Call of Duty : Warzone Loadout App"
          desc="This webapp lists out the best Warzone loadouts to give users the highest possibility of winnning"
        />

        <Cards
          Image={mask}
          title="Face Mask Recognition"
          desc="This app detects whether or not the user is wearing a face mask or not with the help of Machine Learning
          "
        />

        {/* <Cards Image={Image} title="Next JS" desc="TIon know burh" /> */}

        {/* <a href="/about" className={styles.projectCard}>
            <h2>Face-Mask Detector </h2>
            <p>Learn more about who I am</p>
          </a>
          <a href="/about" className={styles.projectCard}>
            <h2>A* Path Finding Algorithm </h2>
            <p>Learn more about who I am</p>
          </a>
          <a href="/about" className={styles.projectCard}>
            <h2> Call of Duty : Warzone Loadout </h2>
            <p>Learn more about who I am</p>
          </a>
          <a href="/about" className={styles.projectCard}>
            <h2>Playstation & Philips Hue Controller</h2>
            <p>Learn more about who I am</p>
          </a>
          <a href="/about" className={styles.projectCard}>
            <h2>Virtual Piano </h2>
            <p>Learn more about who I am</p>
          </a> */}
      </div>

      <footer className={styles.footer}>
        <hr />

        <a href="https://github.com/anmoltyagi1">
          <FaGithub size="2em" color="black" />
        </a>

        <a href="https://www.linkedin.com/in/anmoltyagi1/">
          <FaLinkedin size="2em" color="black" />
        </a>
      </footer>
    </div>
  );
}
